version: "3"
services:
  serversync:
      container_name: serversync
      build: 
          context: ./docker-cron
          dockerfile: ./Dockerfile
          args:
              # cron arg to be used in crontab file
              PERIOD: '0 9 * * *'
              # desination location for rsync
              DEST: 'user@ip:/folder'
      ports:
          - 23:23
          - 873:873
      volumes:
          # log file location
          - /folder/serversync/:/logs
          # source folder for rsync
          - /folder/files/:/src
          # ssh creds 
          - ~/.ssh:/root/.ssh
      restart: unless-stopped
      logging:
          options:
              max-size: 50m
